import {BibleBook, BibleVersion} from '../types/bible';

export const BIBLE_VERSIONS: BibleVersion[] = [
  {
    id: 'RVR1960',
    name: 'Reina Valera 1960',
    abbreviation: 'RVR1960',
    language: 'es',
    year: '1960',
  },
  {
    id: 'KJV',
    name: 'King James Version',
    abbreviation: 'KJV',
    language: 'en',
    year: '1611',
  },
];

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  {
    id: 1,
    name: 'Génesis',
    nameEn: 'Genesis',
    testament: 'old',
    chapters: 50,
    abbr: 'Gn',
    abbrEn: 'Gen',
  },
  {
    id: 2,
    name: 'Éxodo',
    nameEn: 'Exodus',
    testament: 'old',
    chapters: 40,
    abbr: 'Ex',
    abbrEn: 'Exo',
  },
  {
    id: 3,
    name: 'Levítico',
    nameEn: 'Leviticus',
    testament: 'old',
    chapters: 27,
    abbr: 'Lv',
    abbrEn: 'Lev',
  },
  {
    id: 4,
    name: 'Números',
    nameEn: 'Numbers',
    testament: 'old',
    chapters: 36,
    abbr: 'Nm',
    abbrEn: 'Num',
  },
  {
    id: 5,
    name: 'Deuteronomio',
    nameEn: 'Deuteronomy',
    testament: 'old',
    chapters: 34,
    abbr: 'Dt',
    abbrEn: 'Deu',
  },
  {
    id: 6,
    name: 'Josué',
    nameEn: 'Joshua',
    testament: 'old',
    chapters: 24,
    abbr: 'Jos',
    abbrEn: 'Jos',
  },
  {
    id: 7,
    name: 'Jueces',
    nameEn: 'Judges',
    testament: 'old',
    chapters: 21,
    abbr: 'Jue',
    abbrEn: 'Jdg',
  },
  {
    id: 8,
    name: 'Rut',
    nameEn: 'Ruth',
    testament: 'old',
    chapters: 4,
    abbr: 'Rt',
    abbrEn: 'Rut',
  },
  {
    id: 9,
    name: '1 Samuel',
    nameEn: '1 Samuel',
    testament: 'old',
    chapters: 31,
    abbr: '1 S',
    abbrEn: '1Sa',
  },
  {
    id: 10,
    name: '2 Samuel',
    nameEn: '2 Samuel',
    testament: 'old',
    chapters: 24,
    abbr: '2 S',
    abbrEn: '2Sa',
  },
  {
    id: 11,
    name: '1 Reyes',
    nameEn: '1 Kings',
    testament: 'old',
    chapters: 22,
    abbr: '1 R',
    abbrEn: '1Ki',
  },
  {
    id: 12,
    name: '2 Reyes',
    nameEn: '2 Kings',
    testament: 'old',
    chapters: 25,
    abbr: '2 R',
    abbrEn: '2Ki',
  },
  {
    id: 13,
    name: '1 Crónicas',
    nameEn: '1 Chronicles',
    testament: 'old',
    chapters: 29,
    abbr: '1 Cr',
    abbrEn: '1Ch',
  },
  {
    id: 14,
    name: '2 Crónicas',
    nameEn: '2 Chronicles',
    testament: 'old',
    chapters: 36,
    abbr: '2 Cr',
    abbrEn: '2Ch',
  },
  {
    id: 15,
    name: 'Esdras',
    nameEn: 'Ezra',
    testament: 'old',
    chapters: 10,
    abbr: 'Esd',
    abbrEn: 'Ezr',
  },
  {
    id: 16,
    name: 'Nehemías',
    nameEn: 'Nehemiah',
    testament: 'old',
    chapters: 13,
    abbr: 'Neh',
    abbrEn: 'Neh',
  },
  {
    id: 17,
    name: 'Ester',
    nameEn: 'Esther',
    testament: 'old',
    chapters: 10,
    abbr: 'Est',
    abbrEn: 'Est',
  },
  {
    id: 18,
    name: 'Job',
    nameEn: 'Job',
    testament: 'old',
    chapters: 42,
    abbr: 'Job',
    abbrEn: 'Job',
  },
  {
    id: 19,
    name: 'Salmos',
    nameEn: 'Psalms',
    testament: 'old',
    chapters: 150,
    abbr: 'Sal',
    abbrEn: 'Psa',
  },
  {
    id: 20,
    name: 'Proverbios',
    nameEn: 'Proverbs',
    testament: 'old',
    chapters: 31,
    abbr: 'Pr',
    abbrEn: 'Pro',
  },
  {
    id: 21,
    name: 'Eclesiastés',
    nameEn: 'Ecclesiastes',
    testament: 'old',
    chapters: 12,
    abbr: 'Ec',
    abbrEn: 'Ecc',
  },
  {
    id: 22,
    name: 'Cantares',
    nameEn: 'Song of Solomon',
    testament: 'old',
    chapters: 8,
    abbr: 'Cnt',
    abbrEn: 'Son',
  },
  {
    id: 23,
    name: 'Isaías',
    nameEn: 'Isaiah',
    testament: 'old',
    chapters: 66,
    abbr: 'Is',
    abbrEn: 'Isa',
  },
  {
    id: 24,
    name: 'Jeremías',
    nameEn: 'Jeremiah',
    testament: 'old',
    chapters: 52,
    abbr: 'Jer',
    abbrEn: 'Jer',
  },
  {
    id: 25,
    name: 'Lamentaciones',
    nameEn: 'Lamentations',
    testament: 'old',
    chapters: 5,
    abbr: 'Lm',
    abbrEn: 'Lam',
  },
  {
    id: 26,
    name: 'Ezequiel',
    nameEn: 'Ezekiel',
    testament: 'old',
    chapters: 48,
    abbr: 'Ez',
    abbrEn: 'Eze',
  },
  {
    id: 27,
    name: 'Daniel',
    nameEn: 'Daniel',
    testament: 'old',
    chapters: 12,
    abbr: 'Dn',
    abbrEn: 'Dan',
  },
  {
    id: 28,
    name: 'Oseas',
    nameEn: 'Hosea',
    testament: 'old',
    chapters: 14,
    abbr: 'Os',
    abbrEn: 'Hos',
  },
  {
    id: 29,
    name: 'Joel',
    nameEn: 'Joel',
    testament: 'old',
    chapters: 3,
    abbr: 'Jl',
    abbrEn: 'Joe',
  },
  {
    id: 30,
    name: 'Amós',
    nameEn: 'Amos',
    testament: 'old',
    chapters: 9,
    abbr: 'Am',
    abbrEn: 'Amo',
  },
  {
    id: 31,
    name: 'Abdías',
    nameEn: 'Obadiah',
    testament: 'old',
    chapters: 1,
    abbr: 'Abd',
    abbrEn: 'Oba',
  },
  {
    id: 32,
    name: 'Jonás',
    nameEn: 'Jonah',
    testament: 'old',
    chapters: 4,
    abbr: 'Jon',
    abbrEn: 'Jon',
  },
  {
    id: 33,
    name: 'Miqueas',
    nameEn: 'Micah',
    testament: 'old',
    chapters: 7,
    abbr: 'Miq',
    abbrEn: 'Mic',
  },
  {
    id: 34,
    name: 'Nahúm',
    nameEn: 'Nahum',
    testament: 'old',
    chapters: 3,
    abbr: 'Nah',
    abbrEn: 'Nah',
  },
  {
    id: 35,
    name: 'Habacuc',
    nameEn: 'Habakkuk',
    testament: 'old',
    chapters: 3,
    abbr: 'Hab',
    abbrEn: 'Hab',
  },
  {
    id: 36,
    name: 'Sofonías',
    nameEn: 'Zephaniah',
    testament: 'old',
    chapters: 3,
    abbr: 'Sof',
    abbrEn: 'Zep',
  },
  {
    id: 37,
    name: 'Hageo',
    nameEn: 'Haggai',
    testament: 'old',
    chapters: 2,
    abbr: 'Hag',
    abbrEn: 'Hag',
  },
  {
    id: 38,
    name: 'Zacarías',
    nameEn: 'Zechariah',
    testament: 'old',
    chapters: 14,
    abbr: 'Zac',
    abbrEn: 'Zec',
  },
  {
    id: 39,
    name: 'Malaquías',
    nameEn: 'Malachi',
    testament: 'old',
    chapters: 4,
    abbr: 'Mal',
    abbrEn: 'Mal',
  },

  // New Testament
  {
    id: 40,
    name: 'Mateo',
    nameEn: 'Matthew',
    testament: 'new',
    chapters: 28,
    abbr: 'Mt',
    abbrEn: 'Mat',
  },
  {
    id: 41,
    name: 'Marcos',
    nameEn: 'Mark',
    testament: 'new',
    chapters: 16,
    abbr: 'Mc',
    abbrEn: 'Mar',
  },
  {
    id: 42,
    name: 'Lucas',
    nameEn: 'Luke',
    testament: 'new',
    chapters: 24,
    abbr: 'Lc',
    abbrEn: 'Luk',
  },
  {
    id: 43,
    name: 'Juan',
    nameEn: 'John',
    testament: 'new',
    chapters: 21,
    abbr: 'Jn',
    abbrEn: 'Joh',
  },
  {
    id: 44,
    name: 'Hechos',
    nameEn: 'Acts',
    testament: 'new',
    chapters: 28,
    abbr: 'Hch',
    abbrEn: 'Act',
  },
  {
    id: 45,
    name: 'Romanos',
    nameEn: 'Romans',
    testament: 'new',
    chapters: 16,
    abbr: 'Ro',
    abbrEn: 'Rom',
  },
  {
    id: 46,
    name: '1 Corintios',
    nameEn: '1 Corinthians',
    testament: 'new',
    chapters: 16,
    abbr: '1 Co',
    abbrEn: '1Co',
  },
  {
    id: 47,
    name: '2 Corintios',
    nameEn: '2 Corinthians',
    testament: 'new',
    chapters: 13,
    abbr: '2 Co',
    abbrEn: '2Co',
  },
  {
    id: 48,
    name: 'Gálatas',
    nameEn: 'Galatians',
    testament: 'new',
    chapters: 6,
    abbr: 'Gá',
    abbrEn: 'Gal',
  },
  {
    id: 49,
    name: 'Efesios',
    nameEn: 'Ephesians',
    testament: 'new',
    chapters: 6,
    abbr: 'Ef',
    abbrEn: 'Eph',
  },
  {
    id: 50,
    name: 'Filipenses',
    nameEn: 'Philippians',
    testament: 'new',
    chapters: 4,
    abbr: 'Fil',
    abbrEn: 'Phi',
  },
  {
    id: 51,
    name: 'Colosenses',
    nameEn: 'Colossians',
    testament: 'new',
    chapters: 4,
    abbr: 'Col',
    abbrEn: 'Col',
  },
  {
    id: 52,
    name: '1 Tesalonicenses',
    nameEn: '1 Thessalonians',
    testament: 'new',
    chapters: 5,
    abbr: '1 Ts',
    abbrEn: '1Th',
  },
  {
    id: 53,
    name: '2 Tesalonicenses',
    nameEn: '2 Thessalonians',
    testament: 'new',
    chapters: 3,
    abbr: '2 Ts',
    abbrEn: '2Th',
  },
  {
    id: 54,
    name: '1 Timoteo',
    nameEn: '1 Timothy',
    testament: 'new',
    chapters: 6,
    abbr: '1 Ti',
    abbrEn: '1Ti',
  },
  {
    id: 55,
    name: '2 Timoteo',
    nameEn: '2 Timothy',
    testament: 'new',
    chapters: 4,
    abbr: '2 Ti',
    abbrEn: '2Ti',
  },
  {
    id: 56,
    name: 'Tito',
    nameEn: 'Titus',
    testament: 'new',
    chapters: 3,
    abbr: 'Tit',
    abbrEn: 'Tit',
  },
  {
    id: 57,
    name: 'Filemón',
    nameEn: 'Philemon',
    testament: 'new',
    chapters: 1,
    abbr: 'Flm',
    abbrEn: 'Phm',
  },
  {
    id: 58,
    name: 'Hebreos',
    nameEn: 'Hebrews',
    testament: 'new',
    chapters: 13,
    abbr: 'Heb',
    abbrEn: 'Heb',
  },
  {
    id: 59,
    name: 'Santiago',
    nameEn: 'James',
    testament: 'new',
    chapters: 5,
    abbr: 'Stg',
    abbrEn: 'Jam',
  },
  {
    id: 60,
    name: '1 Pedro',
    nameEn: '1 Peter',
    testament: 'new',
    chapters: 5,
    abbr: '1 P',
    abbrEn: '1Pet',
  },
  {
    id: 61,
    name: '2 Pedro',
    nameEn: '2 Peter',
    testament: 'new',
    chapters: 3,
    abbr: '2 P',
    abbrEn: '2Pet',
  },
  {
    id: 62,
    name: '1 Juan',
    nameEn: '1 John',
    testament: 'new',
    chapters: 5,
    abbr: '1 Jn',
    abbrEn: '1Joh',
  },
  {
    id: 63,
    name: '2 Juan',
    nameEn: '2 John',
    testament: 'new',
    chapters: 1,
    abbr: '2 Jn',
    abbrEn: '2Joh',
  },
  {
    id: 64,
    name: '3 Juan',
    nameEn: '3 John',
    testament: 'new',
    chapters: 1,
    abbr: '3 Jn',
    abbrEn: '3Joh',
  },
  {
    id: 65,
    name: 'Judas',
    nameEn: 'Jude',
    testament: 'new',
    chapters: 1,
    abbr: 'Jud',
    abbrEn: 'Jud',
  },
  {
    id: 66,
    name: 'Apocalipsis',
    nameEn: 'Revelation',
    testament: 'new',
    chapters: 22,
    abbr: 'Ap',
    abbrEn: 'Rev',
  },
];

export const getBookByName = (name: string): BibleBook | undefined => {
  return BIBLE_BOOKS.find(
    book =>
      book.name.toLowerCase() === name.toLowerCase() ||
      book.nameEn.toLowerCase() === name.toLowerCase(),
  );
};

export const getBookById = (id: number): BibleBook | undefined => {
  return BIBLE_BOOKS.find(book => book.id === id);
};
