/**
 * Definiciones de todos los logros disponibles
 */

import { Achievement, AchievementCategory, AchievementTier } from './types';

export const ACHIEVEMENT_DEFINITIONS: Omit<Achievement, 'currentProgress' | 'isUnlocked' | 'unlockedAt'>[] = [
  // LOGROS DE LECTURA
  {
    id: 'first_verse',
    name: 'Primeros Pasos',
    description: 'Lee tu primer versículo',
    icon: '👶',
    category: AchievementCategory.READING,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'verses_10',
    name: 'Lector Dedicado',
    description: 'Lee 10 versículos',
    icon: '📖',
    category: AchievementCategory.READING,
    requirement: 10,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'verses_100',
    name: 'Estudiante Aplicado',
    description: 'Lee 100 versículos',
    icon: '📚',
    category: AchievementCategory.READING,
    requirement: 100,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'verses_500',
    name: 'Devoto Lector',
    description: 'Lee 500 versículos',
    icon: '✨',
    category: AchievementCategory.READING,
    requirement: 500,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'verses_1000',
    name: 'Maestro de la Palabra',
    description: 'Lee 1000 versículos',
    icon: '⭐',
    category: AchievementCategory.READING,
    requirement: 1000,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'verses_5000',
    name: 'Erudito Bíblico',
    description: 'Lee 5000 versículos',
    icon: '💎',
    category: AchievementCategory.READING,
    requirement: 5000,
    points: 200,
    tier: AchievementTier.DIAMOND,
  },

  // LOGROS DE RACHAS
  {
    id: 'streak_3',
    name: 'Compromiso Iniciado',
    description: 'Lee 3 días seguidos',
    icon: '🔥',
    category: AchievementCategory.STREAK,
    requirement: 3,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'streak_7',
    name: 'Una Semana Constante',
    description: 'Lee 7 días seguidos',
    icon: '📅',
    category: AchievementCategory.STREAK,
    requirement: 7,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'streak_30',
    name: 'Mes Victorioso',
    description: 'Lee 30 días seguidos',
    icon: '🏆',
    category: AchievementCategory.STREAK,
    requirement: 30,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'streak_100',
    name: 'Disciplina Inquebrantable',
    description: 'Lee 100 días seguidos',
    icon: '💪',
    category: AchievementCategory.STREAK,
    requirement: 100,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'streak_365',
    name: 'Año de Dedicación',
    description: 'Lee 365 días seguidos',
    icon: '👑',
    category: AchievementCategory.STREAK,
    requirement: 365,
    points: 200,
    tier: AchievementTier.DIAMOND,
  },

  // LOGROS DE CAPÍTULOS
  {
    id: 'first_chapter',
    name: 'Primer Capítulo',
    description: 'Completa tu primer capítulo',
    icon: '📄',
    category: AchievementCategory.CHAPTERS,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'chapters_10',
    name: 'Explorador de Capítulos',
    description: 'Completa 10 capítulos',
    icon: '🗺️',
    category: AchievementCategory.CHAPTERS,
    requirement: 10,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'chapters_50',
    name: 'Viajero de la Palabra',
    description: 'Completa 50 capítulos',
    icon: '🚶',
    category: AchievementCategory.CHAPTERS,
    requirement: 50,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'chapters_150',
    name: 'Conquistador de Capítulos',
    description: 'Completa 150 capítulos',
    icon: '⚔️',
    category: AchievementCategory.CHAPTERS,
    requirement: 150,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },

  // LOGROS DE LIBROS
  {
    id: 'first_book',
    name: 'Primer Libro',
    description: 'Completa tu primer libro de la Biblia',
    icon: '📕',
    category: AchievementCategory.BOOKS,
    requirement: 1,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'books_5',
    name: 'Pentateuco Leído',
    description: 'Completa 5 libros',
    icon: '📗',
    category: AchievementCategory.BOOKS,
    requirement: 5,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'books_27',
    name: 'Nuevo Testamento Completo',
    description: 'Completa los 27 libros del NT',
    icon: '✝️',
    category: AchievementCategory.BOOKS,
    requirement: 27,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'books_39',
    name: 'Antiguo Testamento Completo',
    description: 'Completa los 39 libros del AT',
    icon: '📜',
    category: AchievementCategory.BOOKS,
    requirement: 39,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'books_66',
    name: '¡Biblia Completa!',
    description: 'Completa los 66 libros de la Biblia',
    icon: '🎉',
    category: AchievementCategory.BOOKS,
    requirement: 66,
    points: 200,
    tier: AchievementTier.DIAMOND,
  },

  // LOGROS DE DESTACADOS
  {
    id: 'first_highlight',
    name: 'Primera Marca',
    description: 'Crea tu primer destacado',
    icon: '🖍️',
    category: AchievementCategory.HIGHLIGHTS,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'highlights_25',
    name: 'Coleccionista de Tesoros',
    description: 'Crea 25 destacados',
    icon: '💛',
    category: AchievementCategory.HIGHLIGHTS,
    requirement: 25,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'highlights_100',
    name: 'Archivero de Verdades',
    description: 'Crea 100 destacados',
    icon: '🌟',
    category: AchievementCategory.HIGHLIGHTS,
    requirement: 100,
    points: 50,
    tier: AchievementTier.GOLD,
  },

  // LOGROS DE NOTAS
  {
    id: 'first_note',
    name: 'Primera Reflexión',
    description: 'Escribe tu primera nota',
    icon: '📝',
    category: AchievementCategory.NOTES,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'notes_50',
    name: 'Diario Espiritual',
    description: 'Escribe 50 notas',
    icon: '📔',
    category: AchievementCategory.NOTES,
    requirement: 50,
    points: 50,
    tier: AchievementTier.GOLD,
  },

  // LOGROS DE BÚSQUEDA
  {
    id: 'first_search',
    name: 'Buscador de Verdad',
    description: 'Realiza tu primera búsqueda',
    icon: '🔍',
    category: AchievementCategory.SEARCH,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'searches_50',
    name: 'Investigador Diligente',
    description: 'Realiza 50 búsquedas',
    icon: '🔎',
    category: AchievementCategory.SEARCH,
    requirement: 50,
    points: 25,
    tier: AchievementTier.SILVER,
  },

  // LOGROS DE TIEMPO
  {
    id: 'time_60',
    name: 'Una Hora de Lectura',
    description: 'Lee durante 60 minutos acumulados',
    icon: '⏰',
    category: AchievementCategory.TIME,
    requirement: 60,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'time_300',
    name: 'Cinco Horas de Estudio',
    description: 'Lee durante 5 horas acumuladas',
    icon: '⏳',
    category: AchievementCategory.TIME,
    requirement: 300,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'time_1000',
    name: 'Estudiante Dedicado',
    description: 'Lee durante 1000 minutos',
    icon: '📚',
    category: AchievementCategory.TIME,
    requirement: 1000,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },

  // LOGROS ESPECIALES
  {
    id: 'psalms_complete',
    name: 'Salmista',
    description: 'Completa el libro de Salmos',
    icon: '🎵',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'proverbs_complete',
    name: 'Sabio',
    description: 'Completa el libro de Proverbios',
    icon: '💡',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'gospels_complete',
    name: 'Evangelista',
    description: 'Completa los 4 evangelios',
    icon: '📯',
    category: AchievementCategory.SPECIAL,
    requirement: 4,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'early_bird',
    name: 'Madrugador',
    description: 'Lee antes de las 6 AM',
    icon: '🌅',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'night_owl',
    name: 'Búho Nocturno',
    description: 'Lee después de las 11 PM',
    icon: '🦉',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 25,
    tier: AchievementTier.SILVER,
  },
];
