/**
 * Definitions of all available achievements
 */

import { Achievement, AchievementCategory, AchievementTier } from './types';

export const ACHIEVEMENT_DEFINITIONS: Omit<Achievement, 'currentProgress' | 'isUnlocked' | 'unlockedAt'>[] = [
  // READING ACHIEVEMENTS
  {
    id: 'first_verse',
    name: 'First Steps',
    description: 'Read your first verse',
    icon: '👶',
    category: AchievementCategory.READING,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'verses_10',
    name: 'Dedicated Reader',
    description: 'Read 10 verses',
    icon: '📖',
    category: AchievementCategory.READING,
    requirement: 10,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'verses_100',
    name: 'Diligent Student',
    description: 'Read 100 verses',
    icon: '📚',
    category: AchievementCategory.READING,
    requirement: 100,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'verses_500',
    name: 'Devoted Reader',
    description: 'Read 500 verses',
    icon: '✨',
    category: AchievementCategory.READING,
    requirement: 500,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'verses_1000',
    name: 'Word Master',
    description: 'Read 1000 verses',
    icon: '⭐',
    category: AchievementCategory.READING,
    requirement: 1000,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'verses_5000',
    name: 'Biblical Scholar',
    description: 'Read 5000 verses',
    icon: '💎',
    category: AchievementCategory.READING,
    requirement: 5000,
    points: 200,
    tier: AchievementTier.DIAMOND,
  },

  // STREAK ACHIEVEMENTS
  {
    id: 'streak_3',
    name: 'Commitment Started',
    description: 'Read 3 days in a row',
    icon: '🔥',
    category: AchievementCategory.STREAK,
    requirement: 3,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'streak_7',
    name: 'Steady Week',
    description: 'Read 7 days in a row',
    icon: '📅',
    category: AchievementCategory.STREAK,
    requirement: 7,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'streak_30',
    name: 'Victorious Month',
    description: 'Read 30 days in a row',
    icon: '🏆',
    category: AchievementCategory.STREAK,
    requirement: 30,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'streak_100',
    name: 'Unbreakable Discipline',
    description: 'Read 100 days in a row',
    icon: '💪',
    category: AchievementCategory.STREAK,
    requirement: 100,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'streak_365',
    name: 'Year of Dedication',
    description: 'Read 365 days in a row',
    icon: '👑',
    category: AchievementCategory.STREAK,
    requirement: 365,
    points: 200,
    tier: AchievementTier.DIAMOND,
  },

  // CHAPTER ACHIEVEMENTS
  {
    id: 'first_chapter',
    name: 'First Chapter',
    description: 'Complete your first chapter',
    icon: '📄',
    category: AchievementCategory.CHAPTERS,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'chapters_10',
    name: 'Chapter Explorer',
    description: 'Complete 10 chapters',
    icon: '🗺️',
    category: AchievementCategory.CHAPTERS,
    requirement: 10,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'chapters_50',
    name: 'Word Traveler',
    description: 'Complete 50 chapters',
    icon: '🚶',
    category: AchievementCategory.CHAPTERS,
    requirement: 50,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'chapters_150',
    name: 'Chapter Conqueror',
    description: 'Complete 150 chapters',
    icon: '⚔️',
    category: AchievementCategory.CHAPTERS,
    requirement: 150,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },

  // BOOK ACHIEVEMENTS
  {
    id: 'first_book',
    name: 'First Book',
    description: 'Complete your first book of the Bible',
    icon: '📕',
    category: AchievementCategory.BOOKS,
    requirement: 1,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'books_5',
    name: 'Pentateuch Read',
    description: 'Complete 5 books',
    icon: '📗',
    category: AchievementCategory.BOOKS,
    requirement: 5,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'books_27',
    name: 'New Testament Complete',
    description: 'Complete all 27 NT books',
    icon: '✝️',
    category: AchievementCategory.BOOKS,
    requirement: 27,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'books_39',
    name: 'Old Testament Complete',
    description: 'Complete all 39 OT books',
    icon: '📜',
    category: AchievementCategory.BOOKS,
    requirement: 39,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'books_66',
    name: 'Complete Bible!',
    description: 'Complete all 66 books of the Bible',
    icon: '🎉',
    category: AchievementCategory.BOOKS,
    requirement: 66,
    points: 200,
    tier: AchievementTier.DIAMOND,
  },

  // HIGHLIGHT ACHIEVEMENTS
  {
    id: 'first_highlight',
    name: 'First Mark',
    description: 'Create your first highlight',
    icon: '🖍️',
    category: AchievementCategory.HIGHLIGHTS,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'highlights_25',
    name: 'Treasure Collector',
    description: 'Create 25 highlights',
    icon: '💛',
    category: AchievementCategory.HIGHLIGHTS,
    requirement: 25,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'highlights_100',
    name: 'Truth Archivist',
    description: 'Create 100 highlights',
    icon: '🌟',
    category: AchievementCategory.HIGHLIGHTS,
    requirement: 100,
    points: 50,
    tier: AchievementTier.GOLD,
  },

  // NOTE ACHIEVEMENTS
  {
    id: 'first_note',
    name: 'First Reflection',
    description: 'Write your first note',
    icon: '📝',
    category: AchievementCategory.NOTES,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'notes_50',
    name: 'Spiritual Journal',
    description: 'Write 50 notes',
    icon: '📔',
    category: AchievementCategory.NOTES,
    requirement: 50,
    points: 50,
    tier: AchievementTier.GOLD,
  },

  // SEARCH ACHIEVEMENTS
  {
    id: 'first_search',
    name: 'Truth Seeker',
    description: 'Perform your first search',
    icon: '🔍',
    category: AchievementCategory.SEARCH,
    requirement: 1,
    points: 10,
    tier: AchievementTier.BRONZE,
  },
  {
    id: 'searches_50',
    name: 'Diligent Investigator',
    description: 'Perform 50 searches',
    icon: '🔎',
    category: AchievementCategory.SEARCH,
    requirement: 50,
    points: 25,
    tier: AchievementTier.SILVER,
  },

  // TIME ACHIEVEMENTS
  {
    id: 'time_60',
    name: 'One Hour of Reading',
    description: 'Read for 60 accumulated minutes',
    icon: '⏰',
    category: AchievementCategory.TIME,
    requirement: 60,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'time_300',
    name: 'Five Hours of Study',
    description: 'Read for 5 accumulated hours',
    icon: '⏳',
    category: AchievementCategory.TIME,
    requirement: 300,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'time_1000',
    name: 'Dedicated Student',
    description: 'Read for 1000 minutes',
    icon: '📚',
    category: AchievementCategory.TIME,
    requirement: 1000,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },

  // SPECIAL ACHIEVEMENTS
  {
    id: 'psalms_complete',
    name: 'Psalmist',
    description: 'Complete the book of Psalms',
    icon: '🎵',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'proverbs_complete',
    name: 'Wise One',
    description: 'Complete the book of Proverbs',
    icon: '💡',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 50,
    tier: AchievementTier.GOLD,
  },
  {
    id: 'gospels_complete',
    name: 'Evangelist',
    description: 'Complete the 4 gospels',
    icon: '📯',
    category: AchievementCategory.SPECIAL,
    requirement: 4,
    points: 100,
    tier: AchievementTier.PLATINUM,
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Read before 6 AM',
    icon: '🌅',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 25,
    tier: AchievementTier.SILVER,
  },
  {
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Read after 11 PM',
    icon: '🦉',
    category: AchievementCategory.SPECIAL,
    requirement: 1,
    points: 25,
    tier: AchievementTier.SILVER,
  },
];
