/**
 * 🙏 prayer — the pure domain model for the Prayer Companion ("Mi diario de
 * oración", Sprint 93).
 *
 * The app had nothing for prayer beyond the lectio "ORA" step (which appends to
 * a verse note). This adds a private prayer JOURNAL: the reader keeps a list of
 * things they bring to God — by category (the ACTS shape: praise, confession,
 * thanksgiving, supplication, plus intercession for others) — and, when God
 * answers, marks the request answered with a date and an optional testimony so
 * the journal becomes a record of His faithfulness, not a to-do list.
 *
 * This module is PURE (no React / RN / storage / Date.now): every operation
 * takes the current list and returns a NEW list, so it unit-tests
 * deterministically and the screen / store just compose it. Persistence lives
 * in [[prayerStore]]; the daily prayer streak lives in [[prayerLog]]; the guided
 * ACTS session content lives in [[acts]]. Device-local throughout — a prayer
 * journal is private and is never synced.
 *
 * Para la gloria de Dios Todopoderoso ✨
 */

/**
 * The five movements of a balanced prayer life — the classic ACTS pattern
 * (Adoration, Confession, Thanksgiving, Supplication) plus Intercession for the
 * needs of others. Labels live in i18n (`t.prayer.categories[id]`), keyed by id,
 * exactly like the feelings taxonomy.
 */
export type PrayerCategory =
  | 'praise'
  | 'confession'
  | 'thanksgiving'
  | 'supplication'
  | 'intercession';

/** Display order — follows ACTS, with intercession last (prayer for others). */
export const PRAYER_CATEGORY_ORDER: readonly PrayerCategory[] = [
  'praise',
  'confession',
  'thanksgiving',
  'supplication',
  'intercession',
];

/** Per-category icon + accent, theme-independent like the feelings taxonomy. */
export interface PrayerCategoryMeta {
  id: PrayerCategory;
  /** Ionicons glyph for the category chip/badge. */
  icon: string;
  /** Accent hue (hex) — semantic per category, stable across themes. */
  accent: string;
}

export const PRAYER_CATEGORY_META: Record<PrayerCategory, PrayerCategoryMeta> =
  {
    praise: {id: 'praise', icon: 'sparkles', accent: '#f59e0b'},
    confession: {id: 'confession', icon: 'water', accent: '#8b5cf6'},
    thanksgiving: {id: 'thanksgiving', icon: 'gift', accent: '#10b981'},
    supplication: {id: 'supplication', icon: 'hand-left', accent: '#6366f1'},
    intercession: {id: 'intercession', icon: 'people', accent: '#f472b6'},
  };

/** Narrow an arbitrary value to a known {@link PrayerCategory}. */
export function isPrayerCategory(value: unknown): value is PrayerCategory {
  return (
    typeof value === 'string' &&
    Object.prototype.hasOwnProperty.call(PRAYER_CATEGORY_META, value)
  );
}

/** One entry in the prayer journal. */
export interface PrayerRequest {
  /** Stable unique id (uuid-ish; generated by the caller). */
  id: string;
  /** Short headline — what is being brought to God. */
  title: string;
  /** Optional longer note / context. */
  detail?: string;
  category: PrayerCategory;
  /** When it was first written (epoch ms). */
  createdAt: number;
  /** Whether God has answered (moves it to the answered section). */
  answered: boolean;
  /** When it was marked answered (epoch ms), if answered. */
  answeredAt?: number;
  /** Optional testimony of how God answered. */
  answeredNote?: string;
}

/** Length caps so a malformed/huge paste can't bloat device storage. */
export const PRAYER_TITLE_MAX = 120;
export const PRAYER_DETAIL_MAX = 1000;
export const PRAYER_NOTE_MAX = 1000;

/** Trim + collapse + cap a single-line field; returns '' for blank input. */
function clean(value: string | undefined, max: number): string {
  if (typeof value !== 'string') return '';
  return value.trim().slice(0, max);
}

/** True when a title is blank after trimming — the screen blocks adding it. */
export function isBlankTitle(value: string | undefined): boolean {
  return clean(value, PRAYER_TITLE_MAX).length === 0;
}

/**
 * Build a fresh, validated request. The caller supplies the `id` (so this stays
 * pure/testable) and `now`. Title is trimmed/capped; an optional detail is
 * cleaned and dropped when empty. The request starts unanswered.
 */
export function newPrayerRequest(
  fields: {title: string; detail?: string; category: PrayerCategory},
  id: string,
  now: number,
): PrayerRequest {
  const detail = clean(fields.detail, PRAYER_DETAIL_MAX);
  return {
    id,
    title: clean(fields.title, PRAYER_TITLE_MAX),
    ...(detail ? {detail} : {}),
    category: isPrayerCategory(fields.category)
      ? fields.category
      : 'supplication',
    createdAt: now,
    answered: false,
  };
}

/** Prepend a request (newest-first storage order). Pure. */
export function addRequest(
  list: readonly PrayerRequest[],
  request: PrayerRequest,
): PrayerRequest[] {
  return [request, ...list];
}

/** Edit a request's title/detail/category in place (immutably). Pure. */
export function editRequest(
  list: readonly PrayerRequest[],
  id: string,
  fields: {title: string; detail?: string; category: PrayerCategory},
): PrayerRequest[] {
  return list.map(r => {
    if (r.id !== id) return r;
    const detail = clean(fields.detail, PRAYER_DETAIL_MAX);
    const next: PrayerRequest = {
      ...r,
      title: clean(fields.title, PRAYER_TITLE_MAX),
      category: isPrayerCategory(fields.category)
        ? fields.category
        : r.category,
    };
    if (detail) next.detail = detail;
    else delete next.detail;
    return next;
  });
}

/**
 * Mark a request answered, stamping `now` and an optional testimony. Already-
 * answered requests keep their original `answeredAt`. Pure.
 */
export function markAnswered(
  list: readonly PrayerRequest[],
  id: string,
  now: number,
  note?: string,
): PrayerRequest[] {
  return list.map(r => {
    if (r.id !== id) return r;
    const answeredNote = clean(note, PRAYER_NOTE_MAX);
    const next: PrayerRequest = {
      ...r,
      answered: true,
      answeredAt: r.answered && r.answeredAt ? r.answeredAt : now,
    };
    if (answeredNote) next.answeredNote = answeredNote;
    else delete next.answeredNote;
    return next;
  });
}

/** Reopen an answered request (clears its answered stamp + testimony). Pure. */
export function reopenRequest(
  list: readonly PrayerRequest[],
  id: string,
): PrayerRequest[] {
  return list.map(r => {
    if (r.id !== id) return r;
    const next: PrayerRequest = {...r, answered: false};
    delete next.answeredAt;
    delete next.answeredNote;
    return next;
  });
}

/** Remove a request entirely. Pure. */
export function deleteRequest(
  list: readonly PrayerRequest[],
  id: string,
): PrayerRequest[] {
  return list.filter(r => r.id !== id);
}

/** Active (unanswered) requests, newest-first. */
export function activeRequests(
  list: readonly PrayerRequest[],
): PrayerRequest[] {
  return list
    .filter(r => !r.answered)
    .sort((a, b) => b.createdAt - a.createdAt);
}

/** Answered requests, most-recently-answered first. */
export function answeredRequests(
  list: readonly PrayerRequest[],
): PrayerRequest[] {
  return list
    .filter(r => r.answered)
    .sort(
      (a, b) => (b.answeredAt ?? b.createdAt) - (a.answeredAt ?? a.createdAt),
    );
}

/** Filter a list to one category (or pass `'all'` for no filter). */
export function filterByCategory(
  list: readonly PrayerRequest[],
  category: PrayerCategory | 'all',
): PrayerRequest[] {
  if (category === 'all') return [...list];
  return list.filter(r => r.category === category);
}

export interface PrayerStats {
  total: number;
  active: number;
  answered: number;
  /** Count of ACTIVE requests per category (for the filter-chip counts). */
  activeByCategory: Record<PrayerCategory, number>;
}

/** Summary counts for the journal header + Home card. Pure. */
export function prayerStats(list: readonly PrayerRequest[]): PrayerStats {
  const activeByCategory = PRAYER_CATEGORY_ORDER.reduce(
    (acc, c) => {
      acc[c] = 0;
      return acc;
    },
    {} as Record<PrayerCategory, number>,
  );
  let active = 0;
  let answered = 0;
  for (const r of list) {
    if (r.answered) {
      answered += 1;
    } else {
      active += 1;
      if (isPrayerCategory(r.category)) activeByCategory[r.category] += 1;
    }
  }
  return {total: list.length, active, answered, activeByCategory};
}
